### ISSUE TITLE
where is the model?

### ISSUE THREAD

**Issue by gnsci** [Xilinx/DSRL#1]
where is the model?

**Comment by wanglixilinx** [comment]
hi, @gnsci ,
  1) for the weight:  I just provide the *.zip folder containg the weight file, you can unzip it to get the weight.
  2) for the model design file (espnetv2_dsrl.py), beacuse of the liscense conflict between xilinx  and EdgeNet repo, I can only 
  provide the model example file, you can follow my instructions to build the whole model  file.

**Comment by gnsci** [comment]
> hi, @gnsci ,
> 
> 1. for the weight:  I just provide the *.zip folder containg the weight file, you can unzip it to get the weight.
> 2. for the model design file (espnetv2_dsrl.py), beacuse of the liscense conflict between xilinx  and EdgeNet repo, I can only
>    provide the model example file, you can follow my instructions to build the whole model  file.

Got it. Thanks. And where is the instructions and model example file?

**Comment by wanglixilinx** [comment]
I have update the reo files, you can pull the latest one.
